#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Feb 24 09:39:09 2026

@author: zjpeters
"""
import os
import h5py
from scipy.sparse import csr_matrix
import scipy.sparse as sp_sparse
import numpy as np
from matplotlib import pyplot as plt

def loadEntireDatasetFromH5ad(h5adLocation):
    """
    Load a dataset from h5ad file generated by the Allen Institute
    
    *** THIS IS CURRENTLY FORMATTED FOR 'mouse_609882_registered_082725', MAY NOT 
    WORK FOR OTHER SAMPLES ***
    
    Parameters
    ----------
    h5adLocation : filepath
        Location of data to be loaded.

    Returns
    -------
    merscopeDataset : dict
        Dictionary containing the gene matrix, original and CCF coordinates, 
        gene list, and slice codes from a dataset.

    """
    f = h5py.File(h5adLocation)
    x_attrs = dict(f['X'].attrs)
    gene_matrix = sp_sparse.csr_array((f['X']['data'],f['X']['indices'],f['X']['indptr']),x_attrs['shape'])
    # try:
    #     gene_matrix = sp_sparse.csr_array((f['X']['data'],f['X']['indices'],f['X']['indptr']),x_attrs['shape'])
    # except ValueError:
    #     gene_matrix = 
    gene_list = np.array(f['var']['_index'])
    tissue_coordinates = f['obsm']['spatial'][:,0:2]
    # could potentially add slice_codes as the 3rd column in tissue coordinates
    # replacing original below with f['obs']['section']['codes'][:]
    # slice_codes = (f['obs']['brain_section_barcode']['codes'][:])
    slice_codes = f['obs']['section']['codes'][:]
    ccfCoordinates = np.array([f['obs']['x_CCF'][:], f['obs']['y_CCF'][:], f['obs']['z_CCF'][:]]).T
    f.close()
    merscopeDataset = {'geneMatrix': gene_matrix, 'geneList': gene_list, 'tissuePositionCoordinates': tissue_coordinates, 'sliceCodes': slice_codes, 'ccfCoordinates': ccfCoordinates}
    return merscopeDataset

def loadSingleSliceFromH5ad(h5adLocation, zCoord, displayScatter=False):
    """
    Loads a single slice from an h5ad formatted sample from the Allen Institute

    Parameters
    ----------
    h5adLocation : str or file location
        Where the allen data is stored.
    zCoord : int
        Slice location, multiple of 200, i.e. 0, 200, 400, ..., 10000
    displayScatter : bool, optional
        DESCRIPTION. The default is False.

    Returns
    -------
    sample : TYPE
        DESCRIPTION.

    """
    sample = {}
    f = h5py.File(h5adLocation)
    x_attrs = dict(f['X'].attrs)
    # slice_codes = (f['obs']['brain_section_barcode']['codes'][:])
    # slice_codes = f['obs']['section']['codes'][:]
    sample['z_coord'] = f['obs']['z_coord'][:]
    sliceIdx = np.where(sample['z_coord'] == zCoord)[0]
    sample['z_coord'] = f['obs']['z_coord'][sliceIdx]
    try:
        gene_matrix = csr_matrix((f['X']['data'],f['X']['indices'],f['X']['indptr']),x_attrs['shape'])
        sample['geneMatrix'] = gene_matrix[sliceIdx,:]
    except ValueError:
        sample['geneMatrix'] = csr_matrix(f['X'][sliceIdx,:])
    sample['geneList'] = list(np.array(f['var']['_index']))
    # convert byte strings to strings
    for i in range(len(sample['geneList'])):
        sample['geneList'][i] = sample['geneList'][i].decode("utf-8")
    sample['tissuePositionCoordinates'] = f['obsm']['spatial'][sliceIdx,0:2]
    
    x_CCF = f['obs']['x_CCF'][:]
    y_CCF = f['obs']['y_CCF'][:]
    z_CCF = f['obs']['z_CCF'][:]    
    sample['ccfCoordinates'] = np.array([x_CCF[sliceIdx], y_CCF[sliceIdx], z_CCF[sliceIdx]]).T
    f.close()
    if displayScatter == True:
        fig,ax = plt.subplots(1,1)
        ax.scatter(sample['ccfCoordinates'][:,2], sample['ccfCoordinates'][:,1])
        ax.yaxis.set_inverted(True)
        plt.show()
        # plt.figure()
        # plt.scatter(sample['tissuePositionCoordinates'][:,0], sample['tissuePositionCoordinates'][:,1], s=3)
        # plt.show()
    return sample

def loadSingleSliceFromDatedH5ad(h5adLocation, zCoord, displayScatter=False, removeNaNs=True):
    """
    Loads a single slice from an h5ad formatted sample from the Allen Institute

    Parameters
    ----------
    h5adLocation : str or file location
        Where the allen data is stored.
    sliceNumber : int
        Overall slice number, not the slice from CCF.
    displayScatter : bool, optional
        DESCRIPTION. The default is False.

    Returns
    -------
    sample : TYPE
        DESCRIPTION.

    """
    sample = {}
    f = h5py.File(h5adLocation)
    x_attrs = dict(f['X'].attrs)
    # slice_codes = (f['obs']['brain_section_barcode']['codes'][:])
    # slice_codes = f['obs']['brain_section_label']['codes'][:]
    # sliceIdx = np.where(slice_codes == sliceNumber)[0]
    sample['original_filename'] = h5adLocation.split(os.sep)[-1]
    sample['z_coord'] = f['obs']['z_coord'][:]
    # sex and age are stored as strings in the categories section
    sample['sex'] = f['obs']['sex']['categories'][0].decode("utf-8")
    sample['age'] = f['obs']['age']['categories'][0].decode("utf-8")
    sliceIdx = np.where(sample['z_coord'] == zCoord)[0]
    sample['polygon_center'] = np.array([f['obs']['polygon_center_x'][sliceIdx], f['obs']['polygon_center_y'][sliceIdx], f['obs']['polygon_center_z'][sliceIdx]]).T
    if removeNaNs==True:
        nanMask = np.any(~np.isnan(sample['polygon_center']), axis=1)
        sliceIdx = sliceIdx[nanMask]
        sample['polygon_center'] = np.array([f['obs']['polygon_center_x'][sliceIdx], f['obs']['polygon_center_y'][sliceIdx], f['obs']['polygon_center_z'][sliceIdx]]).T
    sample['z_coord'] = f['obs']['z_coord'][sliceIdx]
    try:
        gene_matrix = csr_matrix((f['X']['data'],f['X']['indices'],f['X']['indptr']),x_attrs['shape'])
        sample['geneMatrix'] = gene_matrix[sliceIdx,:]
    except ValueError:
        sample['geneMatrix'] = csr_matrix(f['X'][sliceIdx,:])
    sample['geneList'] = list(np.array(f['var']['_index']))
    # convert byte strings to strings
    for i in range(len(sample['geneList'])):
        sample['geneList'][i] = sample['geneList'][i].decode("utf-8")
    sample['tissuePositionCoordinates'] = f['obsm']['spatial'][sliceIdx,0:2]
    sample['ccfCoordinates'] = np.array([f['obs']['x_CCF'][sliceIdx], f['obs']['y_CCF'][sliceIdx], f['obs']['z_CCF'][sliceIdx]]).T
    # cell type class for each cell is stored in the 'codes' section of the 'hrc_mmc_class_name' key
    sample['cellTypeClassInt'] = f['obs']['hrc_mmc_class_name']['codes'][sliceIdx]
    # the mapping of cell type class integer to a string is stored in the 'categories' section of 'hrc_mmc_class_name'
    sample['cellTypeClassNames'] = f['obs']['hrc_mmc_class_name']['categories'][:]
    for i in range(len(sample['cellTypeClassNames'])):
        sample['cellTypeClassNames'][i] = sample['cellTypeClassNames'][i].decode("utf-8")
    sample['cellTypeClassNames'] = list(sample['cellTypeClassNames'])
    sample['cellTypeClassColorHex'] = np.zeros_like(f['obs']['hrc_mmc_class_color']['codes'][sliceIdx], dtype=np.dtype('U7'))
    for i in range(len(f['obs']['hrc_mmc_class_color']['categories'][:])):
        hexIdx = np.where(f['obs']['hrc_mmc_class_color']['codes'][sliceIdx] == i)[0]
        sample['cellTypeClassColorHex'][hexIdx] = f['obs']['hrc_mmc_class_color']['categories'][i].decode("utf-8")
    sample['ccfID'] = f['obs']['ccf_id'][sliceIdx]
    f.close()
    if displayScatter == True:
        fig,ax = plt.subplots(1,1)
        ax.scatter(sample['ccfCoordinates'][:,2], sample['ccfCoordinates'][:,1])
        ax.yaxis.set_inverted(True)
        plt.show()
        # plt.figure()
        # plt.scatter(sample['tissuePositionCoordinates'][:,0], sample['tissuePositionCoordinates'][:,1], s=3)
        # plt.show()
    return sample

def displaySingleSliceGeneImage(sample, geneList, micronsToDisplay=25, 
                                pixelCombination='additive', displayImage=True, scaleImage=True):
    ### comments below are from before assembling 'sample' dictionary from loadSingleSliceFromH5ad
    # sliceIdx = np.where(slice_codes == sliceNumber)[0]
    slice_coordinates = sample['tissuePositionCoordinates']/micronsToDisplay
    # should double check that this can probably be replaced with 'slice_coordinates'
    image_size = np.round(np.max(sample['tissuePositionCoordinates'], axis=0))/micronsToDisplay
    gene_image = np.zeros([int(image_size[0])+1, int(image_size[1])+1])
    for actGene in enumerate(geneList):
        geneArray = sample['geneMatrix'].todense()[:, [actGene[0]]]
        geneArray = geneArray/np.max(geneArray)
        geneMask = np.squeeze(np.array(geneArray > 0))
        geneCoordinates = slice_coordinates[geneMask,:]
        genePixelNum = actGene[0] + 1
        for coordinate in enumerate(geneCoordinates):
            xCoor = int(coordinate[1][0])
            yCoor = int(coordinate[1][1])
            # print(coordinate[1], xCoor)
            if pixelCombination == 'additive':
                # print(xCoor, yCoor, genePixelNum)
                gene_image[xCoor, yCoor] += genePixelNum
            elif pixelCombination == 'replace':
                gene_image[xCoor, yCoor] = genePixelNum
            elif pixelCombination == 'geneExpressionScaledReplace':
                gene_image[xCoor, yCoor] = genePixelNum * geneArray[:,coordinate[0]]
            elif pixelCombination == 'geneExpressionScaledAdditive':
                gene_image[xCoor, yCoor] += genePixelNum * geneArray[coordinate[0]]
            elif pixelCombination == 'geneExpression':
                gene_image[xCoor, yCoor] += geneArray[coordinate[0]]
    if scaleImage == True:
        gene_image = np.array(gene_image / np.max(gene_image) * 255, dtype='uint8')
    else:
        gene_image = np.array(gene_image)
    if displayImage == True:
        plt.figure()
        plt.imshow(gene_image, cmap='gray')    
        # plt.scatter(slice_coordinates[:,0], slice_coordinates[:,1], s=1)
        plt.show()
    return gene_image

def displaySingleSliceGeneImageCCF(sample, geneList, pixelCombination='additive', 
                                   displayImage=True, scaleImage=True):
    ### comments below are from before assembling 'sample' dictionary from loadSingleSliceFromH5ad
    # sliceIdx = np.where(slice_codes == sliceNumber)[0]
    slice_coordinates = np.array([sample['ccfCoordinates'][:,2], sample['ccfCoordinates'][:,1]]).T
    # should double check that this can probably be replaced with 'slice_coordinates'
    # image_size = np.round(np.max(slice_coordinates, axis=0))
    gene_image = np.zeros([360, 480])
    for actGene in enumerate(geneList):
        geneArray = sample['geneMatrix'].todense()[:, [actGene[0]]]
        geneArray = geneArray/np.max(geneArray)
        geneMask = np.squeeze(np.array(geneArray > 0))
        geneCoordinates = slice_coordinates[geneMask,:]
        genePixelNum = actGene[0] + 1
        for coordinate in enumerate(geneCoordinates):
            xCoor = int(coordinate[1][1])
            yCoor = int(coordinate[1][0])
            # print(coordinate[1], xCoor)
            if pixelCombination == 'additive':
                # print(xCoor, yCoor, genePixelNum)
                gene_image[xCoor, yCoor] += genePixelNum
            elif pixelCombination == 'replace':
                gene_image[xCoor, yCoor] = genePixelNum
            elif pixelCombination == 'geneExpressionScaledReplace':
                gene_image[xCoor, yCoor] = genePixelNum * geneArray[:,coordinate[0]]
            elif pixelCombination == 'geneExpressionScaledAdditive':
                gene_image[xCoor, yCoor] += genePixelNum * geneArray[coordinate[0]]
            elif pixelCombination == 'geneExpression':
                gene_image[xCoor, yCoor] += geneArray[coordinate[0]]
    if scaleImage == True:
        gene_image = np.array(gene_image / np.max(gene_image) * 255, dtype='uint8')
    else:
        gene_image = np.array(gene_image)
    if displayImage == True:
        plt.figure()
        plt.imshow(gene_image, cmap='gray')    
        # plt.scatter(slice_coordinates[:,0], slice_coordinates[:,1], s=1)
        plt.show()
    return gene_image

def viewGeneInSample(sample, gene, setDisplayMax=None):
    try:
        geneIdx = sample['geneList'].index(gene)
        geneArray = np.squeeze(np.array(sample['geneMatrix'][:,geneIdx].todense()))
        fig,ax = plt.subplots(1,1)
        geneScatter = ax.scatter(sample['ccfCoordinates'][:,2], sample['ccfCoordinates'][:,1], c=geneArray, cmap='Reds', s=2, vmax=setDisplayMax, linewidth=0)
        ax.yaxis.set_inverted(True)
        plt.axis('off')
        plt.title(gene)
        fig.colorbar(geneScatter, fraction=0.046, pad=0.04)
        plt.show()
    except ValueError:
        print(f'{gene} not in list')
        
def calculateNativeToCCFTransform(sample, coorType='polygon_center', 
                                  swapDims=True, displayScatter=False):
    """
    Calculate the affine transformation required to transform between native
    and CCF spaces as given in the data

    Parameters
    ----------
    sample : dict
        The sample format generated by the loadSingleSliceFromH5ad function.
    coorType : str, optional
        Which set of coordinates to calculate the transformation from. Default
        is 'polygon_center', could also use 'tissuePositionCoordinates'
    swapDims : bool, optional
        Whether to swap the X and Y coordinate positions in the sample file.
    displayScatter : bool, optional
        Whether to display the comparison of the transformation. The default is False.

    Returns
    -------
    TYPE
        DESCRIPTION.

    """
    if swapDims==True:
        X = np.array([sample[coorType][:,1], sample[coorType][:,0], np.ones_like(sample[coorType][:,0])]).T
        Y = np.array([sample['ccfCoordinates'][:,2], sample['ccfCoordinates'][:,1], np.ones_like(sample['ccfCoordinates'][:,1])]).T
    else:
        X = np.array([sample[coorType][:,0], sample[coorType][:,1], np.ones_like(sample[coorType][:,0])]).T
        Y = np.array([sample['ccfCoordinates'][:,1], sample['ccfCoordinates'][:,2], np.ones_like(sample['ccfCoordinates'][:,1])]).T
        x = np.linalg.lstsq(X,Y, rcond=None)
    x = np.linalg.lstsq(X,Y, rcond=None)

    calculatedCoors = X @ x[0]
    if displayScatter==True:
        fig, ax = plt.subplots(1,3)
        ax[0].scatter(Y[:,0],Y[:,1], s=2)
        ax[0].set_aspect('equal', adjustable='box')
        ax[0].set_title('Original transformation')
        ax[1].scatter(calculatedCoors[:,0], calculatedCoors[:,1], s=2)
        ax[1].set_aspect('equal', adjustable='box')
        ax[1].set_title('Calculated transformation')
        ax[2].scatter(Y[:,0],Y[:,1], s=2)
        ax[2].scatter(calculatedCoors[:,0], calculatedCoors[:,1], s=2, alpha=0.4)
        ax[2].set_aspect('equal', adjustable='box')
        ax[2].set_title('Calculated over CCF')
        plt.show()
    return x[0]

def viewCellTypeInSample(sample, cellType=None):
    if cellType == None:
        fig,ax = plt.subplots(1,1)
        cellTypeScatter = ax.scatter(sample['ccfCoordinates'][:,2], sample['ccfCoordinates'][:,1], c=sample['cellTypeClassColorHex'], s=2, linewidth=0)
        ax.yaxis.set_inverted(True)
        plt.axis('off')
        plt.title('All cell types')
        plt.show()
    elif len(cellType) == 1:
        try:
            cellTypeIdx = sample['cellTypeClassNames'].index(cellType[0])
            cellTypeMask = np.where(sample['cellTypeClassInt'] == cellTypeIdx)[0]
            bgColor = np.zeros_like(sample['cellTypeClassInt'], dtype=np.dtype('U7'))
            bgColor[:] = '#808080'
            fig,ax = plt.subplots(1,1)
            ax.scatter(sample['ccfCoordinates'][:,2], sample['ccfCoordinates'][:,1], c=bgColor, s=2, linewidth=0, alpha=0.4)
            cellTypeScatter = ax.scatter(sample['ccfCoordinates'][cellTypeMask,2], sample['ccfCoordinates'][cellTypeMask,1], c=sample['cellTypeClassColorHex'][cellTypeMask], s=2, linewidth=0)
            ax.yaxis.set_inverted(True)
            plt.axis('off')
            plt.title(cellType[0])
            plt.show()
        except ValueError:
            print(f'{cellType} not in list')
    elif len(cellType) > 1:
        fig,ax = plt.subplots(1,1)
        bgColor = np.zeros_like(sample['cellTypeClassInt'], dtype=np.dtype('U7'))
        bgColor[:] = '#808080'
        ax.scatter(sample['ccfCoordinates'][:,2], sample['ccfCoordinates'][:,1], c=bgColor, s=2, linewidth=0, alpha=0.4)
        titleString = 'Cell types: '
        for actCellType in range(len(cellType)):
            try:
                cellTypeIdx = sample['cellTypeClassNames'].index(cellType[actCellType])
                cellTypeMask = np.where(sample['cellTypeClassInt'] == cellTypeIdx)[0]
                print(len(cellTypeMask))
                cellTypeScatter = ax.scatter(sample['ccfCoordinates'][cellTypeMask,2], sample['ccfCoordinates'][cellTypeMask,1], c=sample['cellTypeClassColorHex'][cellTypeMask], s=2, linewidth=0)                
                print(sample['cellTypeClassColorHex'][cellTypeMask])
                titleString = titleString + cellType[actCellType] + ' '
            except ValueError:
                print(f'{cellType} not in list')
        ax.yaxis.set_inverted(True)
        plt.axis('off')
        plt.title(titleString)
        plt.show()