#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Feb 24 09:39:09 2026

@author: zjpeters
"""
import h5py
from scipy.sparse import csr_matrix
import scipy.sparse as sp_sparse
import numpy as np
from matplotlib import pyplot as plt

def loadEntireDatasetFromH5ad(h5adLocation):
    """
    Load a dataset from h5ad file generated by the Allen Institute
    
    *** THIS IS CURRENTLY FORMATTED FOR 'mouse_609882_registered_082725', MAY NOT 
    WORK FOR OTHER SAMPLES ***
    
    Parameters
    ----------
    h5adLocation : filepath
        Location of data to be loaded.

    Returns
    -------
    merscopeDataset : dict
        Dictionary containing the gene matrix, original and CCF coordinates, 
        gene list, and slice codes from a dataset.

    """
    f = h5py.File(h5adLocation)
    x_attrs = dict(f['X'].attrs)
    gene_matrix = sp_sparse.csr_array((f['X']['data'],f['X']['indices'],f['X']['indptr']),x_attrs['shape'])
    # try:
    #     gene_matrix = sp_sparse.csr_array((f['X']['data'],f['X']['indices'],f['X']['indptr']),x_attrs['shape'])
    # except ValueError:
    #     gene_matrix = 
    gene_list = np.array(f['var']['_index'])
    tissue_coordinates = f['obsm']['spatial'][:,0:2]
    # could potentially add slice_codes as the 3rd column in tissue coordinates
    # replacing original below with f['obs']['section']['codes'][:]
    # slice_codes = (f['obs']['brain_section_barcode']['codes'][:])
    slice_codes = f['obs']['section']['codes'][:]
    ccfCoordinates = np.array([f['obs']['x_CCF'][:], f['obs']['y_CCF'][:], f['obs']['z_CCF'][:]]).T
    f.close()
    merscopeDataset = {'geneMatrix': gene_matrix, 'geneList': gene_list, 'tissuePositionCoordinates': tissue_coordinates, 'sliceCodes': slice_codes, 'ccfCoordinates': ccfCoordinates}
    return merscopeDataset

def loadSingleSliceFromH5ad(h5adLocation, sliceNumber, displayScatter=False):
    """
    Loads a single slice from an h5ad formatted sample from the Allen Institute

    Parameters
    ----------
    h5adLocation : str or file location
        Where the allen data is stored.
    sliceNumber : int
        Overall slice number, not the slice from CCF.
    displayScatter : bool, optional
        DESCRIPTION. The default is False.

    Returns
    -------
    sample : TYPE
        DESCRIPTION.

    """
    sample = {}
    f = h5py.File(h5adLocation)
    x_attrs = dict(f['X'].attrs)
    # slice_codes = (f['obs']['brain_section_barcode']['codes'][:])
    slice_codes = f['obs']['section']['codes'][:]
    sliceIdx = np.where(slice_codes == sliceNumber)[0]
    try:
        gene_matrix = csr_matrix((f['X']['data'],f['X']['indices'],f['X']['indptr']),x_attrs['shape'])
        sample['geneMatrix'] = gene_matrix[sliceIdx,:]
    except ValueError:
        sample['geneMatrix'] = csr_matrix(f['X'][sliceIdx,:])
    sample['geneList'] = list(np.array(f['var']['_index']))
    # convert byte strings to strings
    for i in range(len(sample['geneList'])):
        sample['geneList'][i] = sample['geneList'][i].decode("utf-8")
    sample['tissuePositionCoordinates'] = f['obsm']['spatial'][sliceIdx,0:2]
    
    x_CCF = f['obs']['x_CCF'][:]
    y_CCF = f['obs']['y_CCF'][:]
    z_CCF = f['obs']['z_CCF'][:]    
    sample['ccfCoordinates'] = np.array([x_CCF[sliceIdx], y_CCF[sliceIdx], z_CCF[sliceIdx]]).T
    f.close()
    if displayScatter == True:
        fig,ax = plt.subplots(1,1)
        ax.scatter(sample['ccfCoordinates'][:,2], sample['ccfCoordinates'][:,1])
        ax.yaxis.set_inverted(True)
        plt.show()
        # plt.figure()
        # plt.scatter(sample['tissuePositionCoordinates'][:,0], sample['tissuePositionCoordinates'][:,1], s=3)
        # plt.show()
    return sample

def displaySingleSliceGeneImage(sample, geneList, micronsToDisplay=25, pixelCombination='additive', displayImage=True, scaleImage=True):
    ### comments below are from before assembling 'sample' dictionary from loadSingleSliceFromH5ad
    # sliceIdx = np.where(slice_codes == sliceNumber)[0]
    slice_coordinates = sample['tissuePositionCoordinates']/micronsToDisplay
    # should double check that this can probably be replaced with 'slice_coordinates'
    image_size = np.round(np.max(sample['tissuePositionCoordinates'], axis=0))/micronsToDisplay
    gene_image = np.zeros([int(image_size[0])+1, int(image_size[1])+1])
    for actGene in enumerate(geneList):
        geneArray = sample['geneMatrix'].todense()[:, [actGene[0]]]
        geneArray = geneArray/np.max(geneArray)
        geneMask = np.squeeze(np.array(geneArray > 0))
        geneCoordinates = slice_coordinates[geneMask,:]
        genePixelNum = actGene[0] + 1
        for coordinate in enumerate(geneCoordinates):
            xCoor = int(coordinate[1][0])
            yCoor = int(coordinate[1][1])
            # print(coordinate[1], xCoor)
            if pixelCombination == 'additive':
                # print(xCoor, yCoor, genePixelNum)
                gene_image[xCoor, yCoor] += genePixelNum
            elif pixelCombination == 'replace':
                gene_image[xCoor, yCoor] = genePixelNum
            elif pixelCombination == 'geneExpressionScaledReplace':
                gene_image[xCoor, yCoor] = genePixelNum * geneArray[:,coordinate[0]]
            elif pixelCombination == 'geneExpressionScaledAdditive':
                gene_image[xCoor, yCoor] += genePixelNum * geneArray[coordinate[0]]
            elif pixelCombination == 'geneExpression':
                gene_image[xCoor, yCoor] += geneArray[coordinate[0]]
    if scaleImage == True:
        gene_image = np.array(gene_image / np.max(gene_image) * 255, dtype='uint8')
    else:
        gene_image = np.array(gene_image)
    if displayImage == True:
        plt.figure()
        plt.imshow(gene_image, cmap='gray')    
        # plt.scatter(slice_coordinates[:,0], slice_coordinates[:,1], s=1)
        plt.show()
    return gene_image

def displaySingleSliceGeneImageCCF(sample, geneList, pixelCombination='additive', displayImage=True, scaleImage=True):
    ### comments below are from before assembling 'sample' dictionary from loadSingleSliceFromH5ad
    # sliceIdx = np.where(slice_codes == sliceNumber)[0]
    slice_coordinates = np.array([sample['ccfCoordinates'][:,2], sample['ccfCoordinates'][:,1]]).T
    # should double check that this can probably be replaced with 'slice_coordinates'
    # image_size = np.round(np.max(slice_coordinates, axis=0))
    gene_image = np.zeros([360, 480])
    for actGene in enumerate(geneList):
        geneArray = sample['geneMatrix'].todense()[:, [actGene[0]]]
        geneArray = geneArray/np.max(geneArray)
        geneMask = np.squeeze(np.array(geneArray > 0))
        geneCoordinates = slice_coordinates[geneMask,:]
        genePixelNum = actGene[0] + 1
        for coordinate in enumerate(geneCoordinates):
            xCoor = int(coordinate[1][1])
            yCoor = int(coordinate[1][0])
            # print(coordinate[1], xCoor)
            if pixelCombination == 'additive':
                # print(xCoor, yCoor, genePixelNum)
                gene_image[xCoor, yCoor] += genePixelNum
            elif pixelCombination == 'replace':
                gene_image[xCoor, yCoor] = genePixelNum
            elif pixelCombination == 'geneExpressionScaledReplace':
                gene_image[xCoor, yCoor] = genePixelNum * geneArray[:,coordinate[0]]
            elif pixelCombination == 'geneExpressionScaledAdditive':
                gene_image[xCoor, yCoor] += genePixelNum * geneArray[coordinate[0]]
            elif pixelCombination == 'geneExpression':
                gene_image[xCoor, yCoor] += geneArray[coordinate[0]]
    if scaleImage == True:
        gene_image = np.array(gene_image / np.max(gene_image) * 255, dtype='uint8')
    else:
        gene_image = np.array(gene_image)
    if displayImage == True:
        plt.figure()
        plt.imshow(gene_image, cmap='gray')    
        # plt.scatter(slice_coordinates[:,0], slice_coordinates[:,1], s=1)
        plt.show()
    return gene_image

def viewGeneInSample(sample, gene, setDisplayMax=None):
    try:
        geneIdx = sample['geneList'].index(gene)
        geneArray = np.squeeze(np.array(sample['geneMatrix'][:,geneIdx].todense()))
        fig,ax = plt.subplots(1,1)
        geneScatter = ax.scatter(sample['ccfCoordinates'][:,2], sample['ccfCoordinates'][:,1], c=geneArray, cmap='Reds', s=2, vmax=setDisplayMax)
        ax.yaxis.set_inverted(True)
        plt.title(gene)
        fig.colorbar(geneScatter, fraction=0.046, pad=0.04)
        plt.show()
    except ValueError:
        print(f'{gene} not in list')